#!/usr/bin/env bash
# Row-level validation regression -- docs/testing-guide.md, Phase 2 test #2.
#
# Runs `ingest.cli --dry-run` against every corrupted fixture under
# tests/fixtures/corrupted/ (generated by generate_corrupted_fixtures.py)
# and asserts:
#   1. the dry-run exits 2 (row errors present, per ingest/cli.py's exit
#      code contract -- see docs/phase-2-ingestion.md's module table)
#   2. the WARNING log line for [transactions] contains the case's
#      expected_reason_contains substring
#   3. exactly one row was rejected (24/25 valid, not fewer/more)
#
# Case list and expected reasons are read out of fixture_data.py's sibling,
# generate_corrupted_fixtures.py -- Python is the source of truth for what
# each case asserts; this script just drives ingest.cli against the files
# Python already generated and greps its output.
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
FIXTURES_DIR="$REPO_ROOT/tests/fixtures/corrupted"
FAIL=0

# case_dir:expected_reason_substring -- kept in sync with the CASES dict in
# generate_corrupted_fixtures.py by hand; both are small and change rarely
# enough that a shared JSON file would be more ceremony than it's worth.
CASES=(
  "unrecognized_category:unrecognized category 'NotACategory'"
  "expense_amount_flipped_positive:is expense-type but amount is positive"
  "income_amount_flipped_negative:is income-type but amount is negative"
  "blank_description:empty description"
  "date_outside_budget_month:not the workbook's budget month"
)

for entry in "${CASES[@]}"; do
  case_name="${entry%%:*}"
  expected="${entry#*:}"
  workbook="$FIXTURES_DIR/$case_name/monthly_spreadsheet_Jan_25.xlsx"

  if [[ ! -f "$workbook" ]]; then
    echo "FAIL [$case_name]: fixture not found at $workbook -- did generate_corrupted_fixtures.py run first?"
    FAIL=1
    continue
  fi

  output="$(python3 -m ingest.cli --file "$workbook" --dry-run 2>&1)"
  exit_code=$?

  if [[ $exit_code -ne 2 ]]; then
    echo "FAIL [$case_name]: expected exit code 2 (row errors), got $exit_code"
    echo "$output"
    FAIL=1
    continue
  fi

  if ! grep -qF "$expected" <<<"$output"; then
    echo "FAIL [$case_name]: expected rejection reason containing '$expected', not found in output:"
    echo "$output"
    FAIL=1
    continue
  fi

  if ! grep -qE "Validation: 24/25 transaction rows valid" <<<"$output"; then
    echo "FAIL [$case_name]: expected exactly 24/25 transaction rows valid (one rejection):"
    echo "$output"
    FAIL=1
    continue
  fi

  echo "PASS [$case_name]"
done

if [[ $FAIL -ne 0 ]]; then
  echo
  echo "One or more corrupted-fixture checks failed."
  exit 1
fi

echo
echo "All corrupted-fixture checks passed."
